### ISSUE TITLE
days should be less than 826

### ISSUE THREAD

**Issue by lazymesh** [dakshshah96/local-cert-generator#10]
requirement for trusted certificates has changed to https://support.apple.com/en-us/HT210176

**Comment by dakshshah96** [comment]
Hey @lazymesh, sorry for the late response!

Just released a new version: https://github.com/dakshshah96/local-cert-generator/releases/tag/v1.1.0

Does this fix the issue?

**Comment by MarcGraham** [comment]
Hi, 

Does the root ca need to be limited to less than 826 days? 

I have my root set for 20 years but the server cert to 825 and am able to get chrome to accept the certificate as valid. 

Thanks for the article.

**Comment by dakshshah96** [comment]
Hey @MarcGraham, I think you're right!

Would you like to make a PR for this?

**Comment by MarcGraham** [comment]
Sure, I'll try to get a PR done today

**Comment by dakshshah96** [comment]
This has now been fixed!
