### ISSUE TITLE
Certificate not trusted on iOS 13

### ISSUE THREAD

**Issue by AmauryLiet** [dakshshah96/local-cert-generator#9]
Hey there, thanks a lot for the [article](https://www.freecodecamp.org/news/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec/) and the lib!

The generated certificate isn't trusted by iOS 13 simulators due to Apple new requirements: https://support.apple.com/en-us/HT210176

**Comment by dakshshah96** [comment]
Hey @AmauryLiet, sorry for the late response!

Just made a new release: https://github.com/dakshshah96/local-cert-generator/releases/tag/v1.1.0

Does this fix the issue?
